- name: File Copy
  hosts: all
  remote_user: opc
  tasks:
    - name: Copy file  to remote  machine
      copy:
        content: "This just some text, to be written to a file"
        dest: ~/ansible-tutorial-copy1.txt
